# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-1.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

goflow2:
  name: goflow2
  repository: kubernetes:5000/goflow2:latest
  nodePort: 32001
  kafka: "kafka:9092"
  topic: "sda-flows"

netflowDriver:
  name: flinkjobcluster-netflow-driver
  repository: kubernetes:5000/netflow-source-driver:2.0
  kafka: "kafka:9092"
  input_topic: "sda-flows"
  output_topic: "sda-uni-flows"
  
netflow2bidirectional:
  name: flinkjobcluster-netflow2bidirectional
  repository: kubernetes:5000/netflow2bidirectional-app:2.0
  kafka: "kafka:9092"
  input_topic: "sda-uni-flows"
  output_topic: "sda-bidi-flows"

netflowAggregator:
  name: flinkjobcluster-netflow-aggregator
  repository: kubernetes:5000/netflow-aggregator-app:1.0
  kafka: "kafka:9092"
  input_topic: "sda-bidi-flows"
  output_topic: "sda-netflow-aggregated"

consumerDCP:
  name: flinkjobcluster-netflow-consumer-dcp
  repository: kubernetes:5000/netflow-consumer-driver:4.0
  kafka: "kafka:9092"
  input_topic: "sda-netflow-aggregated"
  output_topic: "netflow-raw"
  
CDS:
  name: crypto-detection-system
  repository: kubernetes:5000/crypto-detector:latest
  kafka: "kafka:9092"
  input_topic: "netflow-raw"
  output_topic: "netflow-anonymized-preprocessed"

flinkConf:
  memory: "2042Mi"
  cpu: "500m"
