apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka-app
        id: "0"
  template:
    metadata:
      labels:
        app: kafka-app
        id: "0"
    spec:
      containers:
      - name: kafka-service
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        #- name: KAFKA_LOG_DIRS
        #  value: "/tmp/kafka-logs"
        - name: KAFKA_BROKER_ID
          value: "0"
        #- name: KAFKA_CREATE_TOPICS
        #  value: test-topic
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-app
    id: "0"
spec:
  ports:
  - name: kafka-port
    port: 9092
    protocol: TCP
  selector:
    app: kafka-app
    id: "0"
  type: LoadBalancer


